### ISSUE TITLE
Clarification on Optical Flow and its Role in Inference

### ISSUE THREAD

**Issue by Noone65536** [Araachie/yoda#1]
Hello,

I recently had the opportunity to read your outstanding paper and found it to be very enlightening. I have a question regarding my understanding of the role of optical flow in your model.

From what I have gathered, it seems that optical flow is only used to generate the supervision signal for pokes and does not participate in the inference process. Is my understanding correct?

Additionally, could you please elaborate on how you convert optical flow into pokes? I am particularly interested in understanding the transformation process, and any insights you could provide would be greatly appreciated.

Thank you very much for your time and consideration. I look forward to your response.

Best Regards,

**Comment by Araachie** [comment]
Hi,

Thank you for your questions. I highly appreciate your interest in our work.

Yes, you are right, optical flow is only used during training. At inference the model responds to user inputs. 

However, optical flow can be used to assess the controllability of our model. For instance, one can apply some control to the initial frame, get the response from the model in the form of the generated second frame, calculate the optical flow between those frames and compare it to the intended control at the interacted pixel (or its neighborhood). We also perform such evaluation in the paper.

The conversion of optical flow into pokes is quite straight-forward. We define a probability density over the pixels in such a way that it is proportional to the optical flow magnitudes at each pixel. We then sample a small set of pixels from that distribution and use the corresponding optical flow vectors as control signals. This randomization at training is essential to enable control over background objects.

**Comment by Noone65536** [comment]
Hello,

Thank you so much for your detailed response! I truly appreciate the time and effort you took to clarify my questions. Looking forward to the code release!

Best Regards,
